project:
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    background: light
    collapse-below: lg
    type: light
    logo: "images/cutcards.gif"
    left: 
      - href: index.qmd
        text: home
      - text: about me
        href: about.qmd
      - text: courses
        menu:
          - M249.qmd
          - M347.qmd
          - M348.qmd
      - text: library
        href: https://www.cardingshed.com/library/
      
    right:
      - icon: github
        href: https://github.com/cardingshed/
      - icon: envelope
        href: mailto:public@richardjohnson.io
    
    page-footer: |
      richard johnson 2023 using 
      ![](/images/quarto.png)
format:
  html:
    theme: litera
    css: bespoke.scss
    toc: true

editor: visual

